/*
ID: 12
The sequence of triangular numbers is generated by adding the natural numbers. So the 7th triangle number would be:
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first 10 terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the 1st trianglular number to have over 5 divisors. What is the value of the first trianglular number 
to have over 500 divisors?
*/
public class ID12 {
    public static int FactorCount(int n) {
        int counter = 0;
        int k = (int) (Math.sqrt(n)) + 1;
        int i;
        for (i = 1; i < k; i++) {
            if (n % i == 0) {
                counter++;
            }
        }
        return 2 * counter;
    }

    public static void main(String[] args) {
        int count = 0;
        int tri_num = 0;
        do {
            count++;
            tri_num += count;
        } while (FactorCount(tri_num) < 500);
        System.out.println(tri_num);
    }
}
//Answer: 76576500
