/*
ID: 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
class ID2 {
	public static int fib(int n) {
		int a = 0, b = 1;
		for (int i = 0; i < n; i++) {
			int c = a;
			a = b;
			b = c + b;
		}
		return a;
	}
	public static void main(String[] args) {
		int sum = 0;
		for (int i = 0; fib(i) <= 4000000; i++)
			if ((fib(i)) % 2 == 0)
				sum += (fib(i));
		System.out.println(sum);
	}
}
//Answer: 4613732
